name: The Crap I Wrote

description: To Make Stuff Work

author: Wouter Saaltink

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, LICENSE.md]
